# Base image
FROM python:3.11.9

# Set the working directory inside the container to /app
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

# Copy the requirements.txt to /app and install dependencies
COPY requirements.txt .   # This copies requirements.txt from the host to /app in the container
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files to /app
COPY . .  

# Expose port 8000 for the Django app
EXPOSE 8000

# Run the Django development server
CMD ["python", "manage.py", "runserver"]
